### ISSUE TITLE
USB NOT RECOGNIZE FOR INSTALL .UF2

### ISSUE THREAD

**Issue by Chris959595** [virtualabs/cutcutgo-bl#4]
i have installed a firmware and flash with result complete, but when power on my cricut maker the usb start but without possibility to insert an .uf2 file view an image, pls help me.
<img width="490" alt="Senza titolo" src="https://github.com/virtualabs/cutcutgo-bl/assets/154564898/f57c0bb6-1738-49df-85fe-089bcc9d97bc">

**Comment by Rockman18** [comment]
Last commit has fixed this issue.
