### ISSUE TITLE
Programming did not complete

### ISSUE THREAD

**Issue by Sz480** [virtualabs/cutcutgo-bl#5]
Hi,

I have two issues while downloading the bootloader. Both points refer to the manual https://virtualabs.github.io/cutcutgo/setup.html.
The first point is solved (https://microchip.my.site.com/s/article/MPLAB-X-Error-message---You-have-selected-the-program-speed-to-Normal) but needs to be updated in the CutCutGo github page.

1. _You have set the program speed to Normal_:
- Task: Starting of the programming of the bootloader.
- Error Message: Script InitJTAG failed with status Type = runScript, Script name = InitJTAG, Status = 0x104. You have set the program speed to Normal. The circuit on your board may require you to slow the speed down. Please change the setting in the tool properties to low and try the operation again.
Programming did not complete.
- It is necessary to have Advanced Mode activated to adjust the Program Speed: Settings (top menu) -> Advanced Mode -> (Default password: microchip)
- Afterwards the program speed can be adjusted to slow: Settings (side menu) -> Snap Tool Option(s) -> Program Speed: Slow

2. _Programming did not complete_:
- Task: Starting of the programming of the bootloader.
- Error Message: Programming did not complete. The requested operation failed because the device appears to be code protected. This may be a result of the device not being properly powered since the Snap tool cannot detect external power.
- I did not find a solution yet. My SNAP is a PG164100. 
- Does the Circut Maker needs to be connected via power supply?

**Comment by virtualabs** [comment]
Hi,

I did not remember having modified the programmer speed during the development of Cutcutgo. But I see your point and it definitely must be added to the setup instructions.

Regarding the programming failure: you need to power your Cricut Maker through its external power supply and then program the MCU. I think the Programming tool may have some option to power the MCU through the debugger port, but not sure if it works with the Cricut Maker. Most of the programming I did with my Cricut Maker was performed while the machine was powered through its external power supply.

**Comment by Sz480** [comment]
Hi @virtualabs,

thanks for the fast answer. 

I can agree when the Circuit Maker was power and on the programming was possible. Maybe this should also included in the setup instructions.

I appreciate your effort to make this project. I am really look forward to using it. For now, I have only some small Python issues with the Inkscape CutCutGo :)

**Comment by Sz480** [comment]
Hi @virtualabs,

thanks for the fast answer.

I can agree when the Circuit Maker was power and on the programming was possible. Maybe this should also included in the setup instructions.

I appreciate your effort to make this project. I am really look forward to using it. For now, I have only some small Python issues with the Inkscape CutCutGo :)
